---
abstract: 'Run a simple IPC session in the same vein as IPC::Run & Expect'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-RunSession-Simple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  IO::Select: 0
  IPC::Open3: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/IPC-RunSession-Simple
version: 0.002
